# Generated by Django 5.2 on 2025-04-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
    ]
